interface Env {
  DATABASE_URL: string;
  AUTH_SECRET: string;
  AUTH_GITHUB_ID: string;
  AUTH_GITHUB_SECRET: string;
  NEXT_PUBLIC_GITHUB_PROFILE_LINK: string;
  DEVELOPMENT_TOKEN: string;
  GITHUB_WEBHOOK_SECRET: string;
  NEXT_PUBLIC_GITHUB_PERSONAL_ACCESS_TOKEN: string;
  NEXTAUTH_URL: string;
  REDIS_HOST_URL: string;
  REDIS_HOST_PORT: string;
  REDIS_HOST_PASSWORD: string;
  GEMINI_API_URL: string;
  GEMINI_API_KEY: string;
  NEXT_PUBLIC_GITHUB_APP_INSTALL_URL?: string;
}

const config: Env = {
  DATABASE_URL: process.env.DATABASE_URL || '',
  AUTH_SECRET: process.env.AUTH_SECRET || '',
  AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID || '',
  AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET || '',
  NEXT_PUBLIC_GITHUB_PROFILE_LINK: process.env.NEXT_PUBLIC_GITHUB_PROFILE_LINK || '',
  DEVELOPMENT_TOKEN: process.env.DEVELOPMENT_TOKEN || '',
  GITHUB_WEBHOOK_SECRET: process.env.GITHUB_WEBHOOK_SECRET || '',
  NEXT_PUBLIC_GITHUB_PERSONAL_ACCESS_TOKEN:
    process.env.NEXT_PUBLIC_GITHUB_PERSONAL_ACCESS_TOKEN || '',
  NEXTAUTH_URL: process.env.NEXTAUTH_URL || '',
  REDIS_HOST_URL: process.env.REDIS_HOST_URL || '',
  REDIS_HOST_PORT: process.env.REDIS_HOST_PORT || '',
  REDIS_HOST_PASSWORD: process.env.REDIS_HOST_PASSWORD || '',
  GEMINI_API_URL: process.env.GEMINI_API_URL || '',
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
  NEXT_PUBLIC_GITHUB_APP_INSTALL_URL: process.env.NEXT_PUBLIC_GITHUB_APP_INSTALL_URL,
};

export default config;
