interface Env {
  DATABASE_URL: string;
  AUTH_SECRET: string;
  AUTH_GITHUB_ID: string;
  AUTH_GITHUB_SECRET: string;
  NEXT_PUBLIC_GITHUB_PROFILE_LINK: string;
  DEVELOPMENT_TOKEN: string;
  GITHUB_WEBHOOK_SECRET: string;
  GITHUB_PERSONAL_ACCESS_TOKEN: string;
  NEXTAUTH_URL: string;
}

const config: Env = {
  DATABASE_URL: process.env.DATABASE_URL!,
  AUTH_SECRET: process.env.AUTH_SECRET!,
  AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID!,
  AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET!,
  NEXT_PUBLIC_GITHUB_PROFILE_LINK: process.env.NEXT_PUBLIC_GITHUB_PROFILE_LINK!,
  DEVELOPMENT_TOKEN: process.env.DEVELOPMENT_TOKEN!,
  GITHUB_WEBHOOK_SECRET: process.env.GITHUB_WEBHOOK_SECRET!,
  GITHUB_PERSONAL_ACCESS_TOKEN: process.env.GITHUB_PERSONAL_ACCESS_TOKEN!,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL!,
};

export default config;
